-- Schema for DJ NOKA AXL Cloudflare D1 SQL Database

-- 1. Table: events
CREATE TABLE IF NOT EXISTS events (
  id TEXT PRIMARY KEY,
  day INTEGER NOT NULL,
  dateStr TEXT NOT NULL,
  clubName TEXT NOT NULL,
  eventTitle TEXT NOT NULL,
  city TEXT NOT NULL,
  country TEXT NOT NULL,
  venueAddress TEXT,
  time TEXT,
  genre TEXT,
  ticketStatus TEXT DEFAULT 'AVAILABLE',
  ticketPrice TEXT,
  flyerImage TEXT,
  supportingDJs TEXT, -- JSON Array string
  description TEXT,
  googleMapsUrl TEXT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 2. Table: bookings (Promoter Inquiries)
CREATE TABLE IF NOT EXISTS bookings (
  id TEXT PRIMARY KEY,
  promoterName TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  eventType TEXT,
  eventDate TEXT,
  venueLocation TEXT,
  estimatedAttendance TEXT,
  budgetTier TEXT,
  message TEXT,
  status TEXT DEFAULT 'UNREAD',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 3. Initial Seed Data: 11 Gigs for NOKA AXL
INSERT OR IGNORE INTO events (id, day, dateStr, clubName, eventTitle, city, country, venueAddress, time, genre, ticketStatus, ticketPrice, flyerImage, supportingDJs, description, googleMapsUrl)
VALUES
(
  'cal-2',
  2,
  'Wednesday, 02 September 2026',
  'VALHALLA JAKARTA',
  'UNDERGROUND TECHNO PROTOCOL',
  'Senopati, South Jakarta',
  'Indonesia',
  'Jl. Senopati No. 74, Kebayoran Baru, Jakarta Selatan',
  '22:00 - 04:00 (Set: 01:00)',
  'Peak Time Hard Techno / Industrial',
  'AVAILABLE',
  'IDR 250,000 (Incl. 1 Drink)',
  '/assets/image-5.jpeg',
  '["Cyber Echo", "Dexter Raw", "Luna V"]',
  'Intense raw underground bass resonance. 4 hours of relentless 142 BPM driving techno beats in Jakarta''s darkest warehouse setting.',
  'https://maps.google.com/?q=Valhalla+Jakarta'
),
(
  'cal-4',
  4,
  'Friday, 04 September 2026',
  'W BALI SEMINYAK',
  'WOOBAR SUNSET SONIC REZONANCE',
  'Seminyak, Bali',
  'Indonesia',
  'Jl. Petitenget, Seminyak, Kerobokan Kelod, Bali',
  '17:00 - 01:00 (Sunset Set: 18:30)',
  'Melodic Techno / Cyber Trance',
  'AVAILABLE',
  'FREE ENTRY (F&B Min. Spend applies)',
  '/assets/image-2.jpeg',
  '["Sunset Pulse", "Damian Cruz"]',
  'Panoramic ocean-view sunset soundscape transitioning from warm hypnotic deep melodic grooves into high-voltage festival energy as darkness falls.',
  'https://maps.google.com/?q=Woobar+W+Bali+Seminyak'
),
(
  'cal-7',
  7,
  'Monday, 07 September 2026',
  'DRAGONFLY JAKARTA',
  'TITANIUM MONDAY NIGHT CLUB RESIDENCY',
  'Gatot Subroto, Jakarta',
  'Indonesia',
  'Graha BIP, Jl. Jend. Gatot Subroto Kav. 23, Jakarta',
  '23:00 - 04:00 (Set: 01:30)',
  'Electro Hard Bounce / Mainstage',
  'FEW TICKETS',
  'IDR 300,000 (Presale 2)',
  '/assets/image-3.jpeg',
  '["DF All-Star Collective", "MC Liquid Voice"]',
  'Jakarta''s most iconic luxury mega-club unleashes NOKA AXL for high-velocity club dynamics and laser-synchronized drop anthems.',
  'https://maps.google.com/?q=Dragonfly+Jakarta'
),
(
  'cal-10',
  10,
  'Thursday, 10 September 2026',
  'COLOSSEUM CLUB JAKARTA',
  'THE 1001 HEARTS OF TECHNO FESTIVAL',
  'Kota Tua, West Jakarta',
  'Indonesia',
  'Jl. Kunir No. 7, Pinangsia, Taman Sari, Jakarta Barat',
  '21:00 - 05:00 (Set: 02:00)',
  'Hard Techno / Psy-Trance Drive',
  'AVAILABLE',
  'IDR 350,000 (Early Entry 22:00)',
  '/assets/image-4.jpeg',
  '["Colosseum resident crew", "VJ Neon Hexagon"]',
  'Massive kinetic kinetic ceiling visuals and Void Acoustics sonic pressure engulfing 3,000+ ravers under NOKA AXL''s midnight orchestration.',
  'https://maps.google.com/?q=Colosseum+Club+Jakarta'
),
(
  'cal-12',
  12,
  'Saturday, 12 September 2026',
  'SAVAYA BALI',
  'CLIFFTOP TEMPLE OF BASS',
  'Uluwatu, Bali',
  'Indonesia',
  'Jl. Belimbing Sari, Banjar Tambiyak, Pecatu, Uluwatu, Bali',
  '16:00 - 00:00 (Headline Set: 21:00)',
  'Festival Big Room / Hard Techno',
  'SOLD OUT',
  'IDR 750,000 (Sold Out)',
  '/assets/image-1.jpeg',
  '["Arya B2B Kazz", "Noxious DJ", "Bali Fire Performers"]',
  'Suspended 100 meters above the Indian Ocean on Uluwatu''s limestone cliffs. The flagship weekend headline set featuring brand-new unreleased ID anthems.',
  'https://maps.google.com/?q=Savaya+Bali'
),
(
  'cal-16',
  16,
  'Wednesday, 16 September 2026',
  'ZOUK SINGAPORE',
  'SOUTHEAST ASIA INVASION TOUR: LEG 1',
  'Clarke Quay',
  'Singapore',
  '3C River Valley Road, #01-05 The Cannery, Singapore',
  '22:00 - 04:00 (Set: 01:00)',
  'Mainstage Cyber Bounce',
  'FEW TICKETS',
  'SGD $60 (Includes 2 Drink Coupons)',
  '/assets/image-2.jpeg',
  '["Zouk Resident Crew", "DJ Jeremy Boon", "MC Fast6"]',
  'NOKA AXL commands the world-famous mainroom at Clarke Quay. Hypnotic futuristic lead synths meets relentless bass drops.',
  'https://maps.google.com/?q=Zouk+Singapore'
),
(
  'cal-18',
  18,
  'Friday, 18 September 2026',
  'ATLAS BEACH CLUB BALI',
  'HOLYWINGS BIGGEST BASS CARNIVAL',
  'Canggu, Bali',
  'Indonesia',
  'Jl. Pantai Berawa No. 88, Canggu, Bali',
  '19:00 - 02:00 (Headline Set: 23:30)',
  'Industrial Rave / Electro Bounce',
  'AVAILABLE',
  'IDR 350,000 (General Admission)',
  '/assets/image-3.jpeg',
  '["Atlas Resident DJs", "Laser Fireworks Crew"]',
  'World''s biggest beach club turns into a monolithic hard electronic dance floor with pyro cannons, CO2 blasters, and 10,000+ partygoers.',
  'https://maps.google.com/?q=Atlas+Beach+Club+Bali'
),
(
  'cal-21',
  21,
  'Monday, 21 September 2026',
  'HW TIGER SURABAYA',
  'MID-EAST JAVA SONIC OVERLOAD',
  'Surabaya, East Java',
  'Indonesia',
  'Jl. Mayjen Sungkono No. 88, Dukuh Pakis, Surabaya',
  '22:00 - 03:30 (Set: 00:30)',
  'Peak Time Club Anthem',
  'AVAILABLE',
  'IDR 200,000',
  '/assets/image-4.jpeg',
  '["Tiger Resident Crew", "DJ Vania"]',
  'East Java ravers unite for an earth-shattering session of high BPM raw club music.',
  'https://maps.google.com/?q=Tiger+Club+Surabaya'
),
(
  'cal-24',
  24,
  'Thursday, 24 September 2026',
  'JIEXPO KEMAYORAN JAKARTA',
  'DWP PRE-PARTY ARENA // ROAD TO DEC 2026',
  'Kemayoran, Jakarta',
  'Indonesia',
  'Gedung Pusat Niaga Arena JIEXPO Kemayoran, Jakarta',
  '18:00 - 02:00 (Set: 22:30)',
  'Mainstage Big Room Techno',
  'AVAILABLE',
  'IDR 550,000 (Official Festival Presale)',
  '/assets/image-5.jpeg',
  '["International Guests", "Dipha Barus", "Whisnu Santika"]',
  'Indonesia''s most prestigious dance music festival gathering. NOKA AXL dominates the indoor hangar arena.',
  'https://maps.google.com/?q=JIEXPO+Kemayoran'
),
(
  'cal-27',
  27,
  'Sunday, 27 September 2026',
  'SHIKU CLUB BANDUNG',
  'PARIS VAN JAVA INTENSE NIGHT',
  'Bandung, West Java',
  'Indonesia',
  'Jl. LLRE Martadinata No. 205, Cihapit, Bandung',
  '22:00 - 04:00 (Set: 01:00)',
  'High Octane Tech-House & Bounce',
  'AVAILABLE',
  'IDR 175,000 (Incl. 1 Cocktail)',
  '/assets/image-1.jpeg',
  '["DJ Ryan B", "Bandung Underground Syndicate"]',
  'Cool mountain breeze outside, pure volcanic fire inside as NOKA AXL tears through Bandung with thunderous kickdrums.',
  'https://maps.google.com/?q=Shiku+Bandung'
),
(
  'cal-30',
  30,
  'Wednesday, 30 September 2026',
  'AGEHA TOKYO (SPECIAL RESURRECTION EVENT)',
  'TOKYO CYBER RAVE 2026',
  'Shin-Kiba, Tokyo',
  'Japan',
  'Shin-Kiba, Koto City, Tokyo, Japan',
  '22:00 - 06:00 (Midnight Countdown Set: 00:00)',
  'Hard Dance / Cyber Techno / J-Core',
  'VIP EXCLUSIVE',
  '¥ 5,500 (Early Bird Sold Out)',
  '/assets/image-5.jpeg',
  '["DJ Taku Takahashi", "Ken Ishii", "Vexen"]',
  'Japan''s legendary clubbing landmark hosts NOKA AXL for a midnight-to-dawn auditory storm as NOKA AXL caps off September with an unforgettable show.',
  'https://maps.google.com/?q=ageHa+Tokyo'
);
