-- SQL Script to Seed October 2026 Tour & Club Calendar Events for DJ NOKA AXL into Cloudflare D1
-- Database: dj-noka-axl-db (ID: c07fcb52-48f0-4c10-b833-5023d39fad31)

-- 1. Ensure events table exists
CREATE TABLE IF NOT EXISTS events (
  id TEXT PRIMARY KEY,
  day INTEGER NOT NULL,
  dateStr TEXT NOT NULL,
  clubName TEXT NOT NULL,
  eventTitle TEXT NOT NULL,
  city TEXT NOT NULL,
  country TEXT NOT NULL,
  venueAddress TEXT,
  time TEXT,
  genre TEXT,
  ticketStatus TEXT DEFAULT 'AVAILABLE',
  ticketPrice TEXT,
  flyerImage TEXT,
  supportingDJs TEXT, -- JSON Array string
  description TEXT,
  googleMapsUrl TEXT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 2. Insert or Replace October 2026 Gigs
INSERT OR REPLACE INTO events (
  id, day, dateStr, clubName, eventTitle, city, country, 
  venueAddress, time, genre, ticketStatus, ticketPrice, 
  flyerImage, supportingDJs, description, googleMapsUrl
)
VALUES
(
  'cal-oct-1',
  1,
  'Thursday, 01 October 2026',
  'SPARTA CLUB JAKARTA',
  'SPARTA THURSDAY ANTHEM // JAKARTA',
  'Jakarta',
  'Indonesia',
  'Sparta Club, Jakarta',
  '22:00 - Late (Set: 00:30)',
  'Breakbeat Full Bass / Jungle Dutch',
  'AVAILABLE',
  'IDR 200,000',
  '/assets/image-1.jpeg',
  '["Sparta Resident DJs", "MC Liquid Voice"]',
  'Opening the October tour with pure high-octane Breakbeat Full Bass energy in Jakarta.',
  'https://maps.google.com/?q=Sparta+Jakarta'
),
(
  'cal-oct-2',
  2,
  'Friday, 02 October 2026',
  'TEMBAK LANGIT BANDUNG X BD',
  'TEMBAK LANGIT X BD // BANDUNG',
  'Bandung',
  'Indonesia',
  'Tembak Langit, Bandung, West Java',
  '22:00 - Late (Set: 01:00)',
  'Breakbeat Full Bass / Hybrid EDM',
  'AVAILABLE',
  'IDR 200,000',
  '/assets/image-2.jpeg',
  '["Tembak Langit Residents", "BD Collective"]',
  'High-voltage collaboration night in Bandung featuring thunderous bass drops and non-stop raving.',
  'https://maps.google.com/?q=Tembak+Langit+Bandung'
),
(
  'cal-oct-3',
  3,
  'Saturday, 03 October 2026',
  'SPARTA CLUB BANDUNG',
  'SPARTA WEEKEND TAKEOVER // BANDUNG',
  'Bandung',
  'Indonesia',
  'Sparta Club, Bandung, West Java',
  '22:00 - Late (Set: 01:00)',
  'Breakbeat Full Bass / Jungle Dutch',
  'AVAILABLE',
  'IDR 200,000',
  '/assets/image-3.jpeg',
  '["Sparta Bandung Crew", "Guest DJ"]',
  'Saturday night peak-time madness at Sparta Bandung with NOKA AXL commanding the dancefloor.',
  'https://maps.google.com/?q=Sparta+Bandung'
),
(
  'cal-oct-8',
  8,
  'Thursday, 08 October 2026',
  'SPARTA CLUB JAKARTA',
  'SPARTA BASS PROTOCOL // JAKARTA',
  'Jakarta',
  'Indonesia',
  'Sparta Club, Jakarta',
  '22:00 - Late (Set: 00:30)',
  'Breakbeat Full Bass / Mainstage EDM',
  'AVAILABLE',
  'IDR 200,000',
  '/assets/image-4.jpeg',
  '["Sparta Jakarta All-Stars"]',
  'Relentless bass frequencies and fast syncopated beats return to Sparta Jakarta.',
  'https://maps.google.com/?q=Sparta+Jakarta'
),
(
  'cal-oct-9',
  9,
  'Friday, 09 October 2026',
  'THE NINE MALANG',
  'THE NINE EAST JAVA SENSATION // MALANG',
  'Malang',
  'Indonesia',
  'The Nine Club & KTV, Malang, East Java',
  '22:00 - Late (Set: 01:00)',
  'Breakbeat Full Bass / Drop Bass',
  'AVAILABLE',
  'IDR 200,000',
  '/assets/image-5.jpeg',
  '["The Nine Resident DJs", "MC Giri"]',
  'NOKA AXL invades Malang with signature viral breakbeat hits and ground-shaking drops.',
  'https://maps.google.com/?q=The+Nine+Malang'
),
(
  'cal-oct-10',
  10,
  'Saturday, 10 October 2026',
  'SPARTA CLUB BANDUNG',
  'SPARTA SATURDAY BLAST // BANDUNG',
  'Bandung',
  'Indonesia',
  'Sparta Club, Bandung, West Java',
  '22:00 - Late (Set: 01:00)',
  'Breakbeat Full Bass / Jungle Dutch',
  'AVAILABLE',
  'IDR 200,000',
  '/assets/image-6.jpeg',
  '["Sparta Bandung Residents"]',
  'Saturday night energy unleashed in Bandung with volcanic kicks and electrifying rhythms.',
  'https://maps.google.com/?q=Sparta+Bandung'
),
(
  'cal-oct-15',
  15,
  'Thursday, 15 October 2026',
  'SPARTA CLUB JAKARTA',
  'SPARTA MID-MONTH MADNESS // JAKARTA',
  'Jakarta',
  'Indonesia',
  'Sparta Club, Jakarta',
  '22:00 - Late (Set: 00:30)',
  'Breakbeat Full Bass / Jungle Dutch',
  'AVAILABLE',
  'IDR 200,000',
  '/assets/image-7.jpeg',
  '["Sparta Jakarta Crew"]',
  'Mid-month electric club experience with NOKA AXL driving Jakarta ravers wild.',
  'https://maps.google.com/?q=Sparta+Jakarta'
),
(
  'cal-oct-16',
  16,
  'Friday, 16 October 2026',
  'TEMBAK LANGIT BSD',
  'TEMBAK LANGIT BASS REVOLUTION // BSD',
  'BSD, Tangerang',
  'Indonesia',
  'Tembak Langit, BSD City, Tangerang',
  '22:00 - Late (Set: 01:00)',
  'Breakbeat Full Bass / Hybrid EDM',
  'AVAILABLE',
  'IDR 200,000',
  '/assets/image-1.jpeg',
  '["Tembak Langit Resident Crew"]',
  'BSD Tangerang gets ready for an explosive night of heavy breakbeat and festival anthems.',
  'https://maps.google.com/?q=Tembak+Langit+BSD'
),
(
  'cal-oct-17',
  17,
  'Saturday, 17 October 2026',
  'SPARTA CLUB BANDUNG',
  'SPARTA HIGH OCTANE // BANDUNG',
  'Bandung',
  'Indonesia',
  'Sparta Club, Bandung, West Java',
  '22:00 - Late (Set: 01:00)',
  'Breakbeat Full Bass / Jungle Dutch',
  'AVAILABLE',
  'IDR 200,000',
  '/assets/image-2.jpeg',
  '["Sparta Bandung Sound System"]',
  'Bandung weekend party reaches its peak with NOKA AXL delivering high-octane soundscapes.',
  'https://maps.google.com/?q=Sparta+Bandung'
),
(
  'cal-oct-19',
  19,
  'Monday, 19 October 2026',
  'ESKALA YOGYAKARTA',
  'ESKALA JOGJA NIGHT RAVE // YOGYAKARTA',
  'Yogyakarta',
  'Indonesia',
  'Eskala Eatery Bar & Tent, Sleman, Yogyakarta',
  '21:00 - Late (Set: 23:30)',
  'Breakbeat Full Bass / Viral Anthems',
  'AVAILABLE',
  'IDR 150,000',
  '/assets/image-3.jpeg',
  '["Eskala Resident DJs", "Jogja Bass Syndicate"]',
  'Special Monday night showcase in Yogyakarta with an unforgettable atmosphere at Eskala.',
  'https://maps.google.com/?q=Eskala+Yogyakarta'
),
(
  'cal-oct-22',
  22,
  'Thursday, 22 October 2026',
  'SPARTA CLUB JAKARTA',
  'SPARTA NIGHT PROTOCOL // JAKARTA',
  'Jakarta',
  'Indonesia',
  'Sparta Club, Jakarta',
  '22:00 - Late (Set: 00:30)',
  'Breakbeat Full Bass / Jungle Dutch',
  'AVAILABLE',
  'IDR 200,000',
  '/assets/image-4.jpeg',
  '["Sparta Jakarta Residents"]',
  'Intense raw underground bass and signature drops at Sparta Club Jakarta.',
  'https://maps.google.com/?q=Sparta+Jakarta'
),
(
  'cal-oct-23',
  23,
  'Friday, 23 October 2026',
  'EXODUS KENDARI',
  'EXODUS SULAWESI INVASION // KENDARI',
  'Kendari',
  'Indonesia',
  'Exodus Club, Kendari, Southeast Sulawesi',
  '22:00 - Late (Set: 01:00)',
  'Breakbeat Full Bass / Hard Bounce',
  'AVAILABLE',
  'IDR 250,000',
  '/assets/image-5.jpeg',
  '["Exodus Resident Lineup", "MC Venom"]',
  'Southeast Sulawesi leg of the tour — NOKA AXL sets Exodus Kendari on fire with massive energy.',
  'https://maps.google.com/?q=Exodus+Kendari'
),
(
  'cal-oct-24',
  24,
  'Saturday, 24 October 2026',
  'SPARTA CLUB BANDUNG',
  'SPARTA WEEKEND CARNIVAL // BANDUNG',
  'Bandung',
  'Indonesia',
  'Sparta Club, Bandung, West Java',
  '22:00 - Late (Set: 01:00)',
  'Breakbeat Full Bass / Jungle Dutch',
  'AVAILABLE',
  'IDR 200,000',
  '/assets/image-6.jpeg',
  '["Sparta Bandung All-Stars"]',
  'Saturday night fever in Paris van Java with thunderous low-end and festival vibes.',
  'https://maps.google.com/?q=Sparta+Bandung'
),
(
  'cal-oct-25',
  25,
  'Sunday, 25 October 2026',
  'GOZADERA SURABAYA',
  'GOZADERA SUNDAY FIESTA // SURABAYA',
  'Surabaya',
  'Indonesia',
  'Gozadera Bar & Eatery, Surabaya, East Java',
  '21:00 - Late (Set: 23:30)',
  'Breakbeat Full Bass / Latin Bounce',
  'AVAILABLE',
  'IDR 200,000',
  '/assets/image-7.jpeg',
  '["Gozadera Resident Crew"]',
  'Sunday special edition in Surabaya featuring infectious rhythms and explosive basslines.',
  'https://maps.google.com/?q=Gozadera+Surabaya'
),
(
  'cal-oct-28',
  28,
  'Wednesday, 28 October 2026',
  'KANTOR SURABAYA',
  'KANTOR SURABAYA MIDWEEK MADNESS // SURABAYA',
  'Surabaya',
  'Indonesia',
  'Kantor Bar & Lounge, Surabaya, East Java',
  '22:00 - Late (Set: 00:30)',
  'Breakbeat Full Bass / Jungle Dutch',
  'AVAILABLE',
  'IDR 200,000',
  '/assets/image-1.jpeg',
  '["Kantor Surabaya Residents"]',
  'Midweek rave overload at Kantor Surabaya with NOKA AXL spinning hard-hitting tracks.',
  'https://maps.google.com/?q=Kantor+Surabaya'
),
(
  'cal-oct-29',
  29,
  'Thursday, 29 October 2026',
  'HEXA TULUNGAGUNG',
  'HEXA CLUB OVERDRIVE // TULUNGAGUNG',
  'Tulungagung',
  'Indonesia',
  'Hexa Club & Lounge, Tulungagung, East Java',
  '22:00 - Late (Set: 00:30)',
  'Breakbeat Full Bass / Drop Bass',
  'AVAILABLE',
  'IDR 150,000',
  '/assets/image-2.jpeg',
  '["Hexa Resident DJs"]',
  'East Java tour continues in Tulungagung with an electric atmosphere and signature drops.',
  'https://maps.google.com/?q=Hexa+Tulungagung'
),
(
  'cal-oct-30',
  30,
  'Friday, 30 October 2026',
  'GREEN HOUSE BALIKPAPAN',
  'GREEN HOUSE BORNEO RAVE // BALIKPAPAN',
  'Balikpapan',
  'Indonesia',
  'Green House, Balikpapan, East Kalimantan',
  '22:00 - Late (Set: 01:00)',
  'Breakbeat Full Bass / Hybrid EDM',
  'AVAILABLE',
  'IDR 250,000',
  '/assets/image-3.jpeg',
  '["Green House Resident Lineup"]',
  'Borneo dancefloor takeover at Green House Balikpapan with top tier sound and lighting.',
  'https://maps.google.com/?q=Green+House+Balikpapan'
),
(
  'cal-oct-31',
  31,
  'Saturday, 31 October 2026',
  'SPARTA CLUB BANDUNG',
  'SPARTA HALLOWEEN SPECIAL CLOSING // BANDUNG',
  'Bandung',
  'Indonesia',
  'Sparta Club, Bandung, West Java',
  '22:00 - Late (Set: 01:00)',
  'Breakbeat Full Bass / Jungle Dutch',
  'AVAILABLE',
  'IDR 250,000',
  '/assets/image-4.jpeg',
  '["Sparta Bandung All-Stars", "Halloween Special Visuals"]',
  'Grand Halloween closing party of October Tour 2026 at Sparta Bandung. Full bass costume rave!',
  'https://maps.google.com/?q=Sparta+Bandung'
);
